- name: Provision a new instance
  hosts: all
  tasks:
    - name: Add signing key for Caddy repository
      # Adapted from https://caddyserver.com/docs/install#debian-ubuntu-raspbian.
      become: true
      block:
        - ansible.builtin.get_url:
            url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
            dest: /etc/apt/keyrings/caddy.asc
        - ansible.builtin.apt_repository:
            repo: deb [signed-by=/etc/apt/keyrings/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    - name: Add Docker repository
      # Adapted from https://docs.docker.com/engine/install/ubuntu/.
      become: true
      block:
        - name: Add Docker repository - Download signing key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
        - name: Add Docker repository - 
          ansible.builtin.apt_repository:
            repo: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    - name: Install Caddy and Docker
      become: true
      ansible.builtin.apt:
        name:
          - caddy
          # We use Docker even though The Lounge provides a plain Ubuntu package
          # because the plain Ubuntu package compiles SQLite at install time, which
          # seems to bump up against our instance's memory limits.
          - docker-ce
          - docker-ce-cli
    - name: Configure Caddy
      become: true
      block:
        - ansible.builtin.template:
            src: files/Caddyfile.j2
            dest: /etc/caddy/Caddyfile
        - ansible.builtin.systemd:
            name: caddy
            state: reloaded
    - name: Create system user for The Lounge
      become: true
      ansible.builtin.user:
        name: thelounge
        system: true
        create_home: false
        shell: /usr/sbin/nologin
        password_lock: true
      register: thelounge_user_result
    - name: Create state directory for The Lounge
      become: true
      ansible.builtin.file:
        path: /var/opt/thelounge
        state: directory
        owner: thelounge
        group: thelounge
        mode: u=rwx,g=,o=
    - name: Create configuration file for The Lounge
      become: true
      ansible.builtin.copy:
        src: files/config.js
        dest: /var/opt/thelounge/config.js
        owner: thelounge
        group: thelounge
        mode: u=rw,g=,o=
    - name: Install service file for The Lounge
      become: true
      block:
        - ansible.builtin.template:
            src: files/thelounge.service.j2
            dest: /etc/systemd/system/thelounge.service
        - ansible.builtin.systemd:
            daemon_reload: true
    - name: Install thelounge-docker-exec
      become: true
      ansible.builtin.copy:
        src: files/thelounge-docker-exec
        dest: /usr/local/bin/thelounge-docker-exec
        mode: a+x
    - name: Enable and start The Lounge
      become: true
      ansible.builtin.systemd:
        name: thelounge
        enabled: true
        state: started