- name: Provision a new instance
  hosts: thelounge

  roles:
    # Installing The Lounge appears to involve compiling a SQLite binding,
    # which exhausts a t4g.nano's RAM.
    - role: geerlingguy.swap
      become: true
      swap_file_size_mb: '1024'

    - role: hifis.unattended_upgrades
      become: true
      unattended_origins_patterns:
        # From the Ubuntu official repositories, just install security upgrades.
        # This is the hifis.unattended_upgrades default.
        - 'origin=Ubuntu,archive=${distro_codename}-security,label=Ubuntu'
        # From the Caddy and Node repositories, install all upgrades.
        # Ideally, we'd just install security upgrades,
        # but these repositories aren't split up in a way that supports that kind of filtering.
        - site=dl.cloudsmith.io
        - site=deb.nodesource.com

      unattended_remove_unused_dependencies: true
      unattended_remove_unused_kernel_packages: true
      unattended_automatic_reboot: true
      unattended_ignore_apps_require_restart: true
      unattended_syslog_enable: true

  tasks:
    # Adapted from https://caddyserver.com/docs/install#debian-ubuntu-raspbian.
    - name: Add signing key for Caddy repository
      become: true
      ansible.builtin.get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        dest: /etc/apt/keyrings/caddy.asc
        mode: u=rw,g=r,o=r
    - name: Add Caddy repository
      become: true
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main

    # Adapted from https://github.com/nodesource/distributions#deb.
    - name: Add signing key for Node repository
      become: true
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        dest: /etc/apt/keyrings/node.asc
        mode: u=rw,g=r,o=r
    - name: Add Node repository
      become: true
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/node.asc] https://deb.nodesource.com/node_18.x jammy main

    - name: Install Caddy and Node
      become: true
      ansible.builtin.apt:
        name:
          - caddy
          - nodejs

    - name: Install The Lounge
      become: true
      ansible.builtin.apt:
        deb: https://github.com/thelounge/thelounge-deb/releases/download/v4.4.1/thelounge_4.4.1_all.deb

    - name: Configure Caddy
      become: true
      ansible.builtin.template:
        src: files/Caddyfile.j2
        dest: /etc/caddy/Caddyfile
        owner: caddy
        group: caddy
        mode: u=rw,g=rw,o=
      notify: Reload Caddy

    - name: Configure The Lounge
      become: true
      ansible.builtin.copy:
        src: files/config.js
        dest: /etc/thelounge/config.js
        owner: thelounge
        group: thelounge
        mode: u=rw,g=,o=
      notify: Restart The Lounge

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    # It's probably already enabled and started by default,
    # but make sure anyway.
    - name: Enable and start The Lounge
      become: true
      ansible.builtin.systemd:
        name: thelounge
        enabled: true
        state: started

  handlers:
    - name: Restart The Lounge
      become: true
      ansible.builtin.systemd:
        name: thelounge
        state: restarted

    - name: Reload Caddy
      become: true
      ansible.builtin.systemd:
        name: caddy
        state: reloaded
